version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    networks:
      - portainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates.json:/templates.json
      - ./portainer_password:/tmp/portainer_password
      - ./template_data:/template_data
    command: ["-H", "unix:///var/run/docker.sock", "--admin-password-file", "/tmp/portainer_password", "--template-file", "/templates.json"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  #http://portainer-templates/templates.json
  # portainer-templates:
  #   image: base22/portainer-templates:latest
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - portainer-net
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]

networks:
  portainer-net: